### ISSUE TITLE
Is there docs or wiki on how to properly set  ignite 

### ISSUE THREAD

**Issue by devocodes** [ebean-orm/ebean-ignite#5]
I add ebean ignite dependence to my maven artifact and then I add @Cache on an entity when I start the server, I get this error

``` java
17:33:53.925 [main] ERROR io.ebean.Ebean - Error trying to create the default EbeanServer
java.lang.AbstractMethodError: io.ebean.ignite.IgCacheFactory.createCache(Lio/ebean/cache/ServerCacheType;Ljava/lang/String;Lio/ebean/cache/ServerCacheOptions;)Lio/ebean/cache/ServerCache;
	at io.ebeaninternal.server.cache.DefaultCacheHolder.createCache(DefaultCacheHolder.java:65)
	at io.ebeaninternal.server.cache.DefaultCacheHolder.lambda$getCacheInternal$0(DefaultCacheHolder.java:60)
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
	at io.ebeaninternal.server.cache.DefaultCacheHolder.getCacheInternal(DefaultCacheHolder.java:60)
	at io.ebeaninternal.server.cache.DefaultCacheHolder.getCache(DefaultCacheHolder.java:45)
	at io.ebeaninternal.server.cache.DefaultServerCacheManager.getBeanCache(DefaultServerCacheManager.java:73)
	at io.ebeaninternal.server.deploy.BeanDescriptorCacheHelp.<init>(BeanDescriptorCacheHelp.java:96)
	at io.ebeaninternal.server.deploy.BeanDescriptor.<init>(BeanDescriptor.java:487)
	at io.ebeaninternal.server.deploy.BeanDescriptorManager.readEntityRelationships(BeanDescriptorManager.java:759)
	at io.ebeaninternal.server.deploy.BeanDescriptorManager.deploy(BeanDescriptorManager.java:328)
	at io.ebeaninternal.server.core.InternalConfiguration.<init>(InternalConfiguration.java:141)
	at io.ebeaninternal.server.core.DefaultContainer.createServer(DefaultContainer.java:130)
	at io.ebeaninternal.server.core.DefaultContainer.createServer(DefaultContainer.java:79)
	at io.ebeaninternal.server.core.DefaultContainer.createServer(DefaultContainer.java:44)
	at io.ebean.EbeanServerFactory.create(EbeanServerFactory.java:55)
	at io.ebean.Ebean$ServerManager.getWithCreate(Ebean.java:201)
	at io.ebean.Ebean$ServerManager.<init>(Ebean.java:159)
	at io.ebean.Ebean$ServerManager.<init>(Ebean.java:124)
	at io.ebean.Ebean.<clinit>(Ebean.java:118)

```

**Comment by devocodes** [comment]
OK, after trial and error i figured it out, I was using legacy ebean version.
